import type { WorkbenchData } from "./types";

export const workbenchData: WorkbenchData = {
  goal: {
    id: "GOAL-ARIADNE-1",
    title: "Ariadne v1.0: local AI builder workbench",
    northStar:
      "让知识、反馈和代码状态持续更新 ticket，再把明确的 ticket 分配给 Codex / Claude / fake-codex 执行。",
    status: "active",
    knowledgeInputs: [
      "Multica issue-agent-runtime-board architecture",
      "Ariadne ADR-0004 ticket-centered agent workbench",
      "Execution feedback from fake-codex and CodexBackend smoke path",
    ],
    feedbackSignals: [
      "Goal 只能作为输入，不再是中心对象",
      "前端需要对标 Multica 的成熟产品形态",
      "用户需要可见的 ticket lifecycle 和 agent progress",
    ],
    currentState: "Python local core works through CLI and static board.",
    targetState: "Independent workbench frontend with goal, ticket, agent, runtime, skill, inbox, and progress pages.",
  },
  tickets: [
    {
      id: "t-1",
      key: "ARI-FE-001",
      title: "Build Multica-style Ariadne app shell",
      summary: "Sidebar, topbar, workspace navigation, and floating agent chat dock.",
      status: "running",
      priority: "high",
      owner: "Ariadne Codex",
      source: "Multica app-sidebar and issues screenshot",
      decision: "code_task",
      changedFiles: ["frontend/ariadne-workbench/src/App.tsx", "frontend/ariadne-workbench/src/styles.css"],
      progress: [
        { time: "09:10", actor: "Codex", kind: "analysis", body: "Captured Multica issues, agents, runtimes, skills, inbox screenshots." },
        { time: "09:18", actor: "Codex", kind: "implementation", body: "Started local React workbench with Ariadne goal adaptation." },
      ],
      reviewVerdict: "pending",
      acceptance: [
        "Sidebar matches Multica information density.",
        "The /goal page is first-class.",
        "No hosted auth or Multica runtime dependency is introduced.",
      ],
    },
    {
      id: "t-2",
      key: "ARI-FE-002",
      title: "Implement ticket board and detail inspector",
      summary: "Kanban board with status columns and right-hand detail timeline.",
      status: "reviewing",
      priority: "high",
      owner: "Ariadne Implementer",
      source: "Multica Issues and IssueDetail components",
      decision: "code_task",
      changedFiles: ["src/components/IssueBoard.tsx", "src/components/TicketDetail.tsx"],
      progress: [
        { time: "08:42", actor: "Ariadne Implementer", kind: "handoff", body: "Ticket board should expose packet, backend, tests, review, memory." },
        { time: "08:57", actor: "Ariadne Reviewer", kind: "review", body: "Need stronger progress timeline and memory path visibility." },
      ],
      reviewVerdict: "needs_fix",
      memoryPath: ".ariadne/memory/tickets/ARI-003.json",
      nextTicketsPath: ".ariadne/artifacts/ARI-003/next_tickets.json",
      acceptance: [
        "Each ticket card shows owner, decision, and review state.",
        "Detail inspector shows changed files and acceptance criteria.",
      ],
    },
    {
      id: "t-3",
      key: "ARI-FE-003",
      title: "Expose agent roles and runtime capability",
      summary: "Agents, runtimes, and skills pages adapted to Ariadne local core.",
      status: "planning",
      priority: "medium",
      owner: "Ariadne Reviewer",
      source: "Multica agents, runtimes, skills pages",
      decision: "doc_update",
      changedFiles: [],
      progress: [
        { time: "08:20", actor: "Build Lead", kind: "route", body: "Keep Codex, Reviewer, Release Verifier, and fake-codex visible as teammates." },
      ],
      reviewVerdict: "pending",
      acceptance: [
        "Agent roles are visible.",
        "Runtime capabilities show local safety gates.",
        "Skills show attached BuildSkill packs.",
      ],
    },
    {
      id: "t-4",
      key: "ARI-FE-004",
      title: "Wire inbox into review and blocker events",
      summary: "Show comments, blockers, memory writes, and feedback events as a work queue.",
      status: "inbox",
      priority: "medium",
      owner: "Build Lead",
      source: "Multica inbox page",
      decision: "architecture_change",
      changedFiles: [],
      progress: [],
      reviewVerdict: "pending",
      acceptance: [
        "Inbox separates review, blocker, memory, and goal feedback.",
        "Each item links back to ticket or goal context.",
      ],
    },
    {
      id: "t-5",
      key: "ARI-FE-005",
      title: "Finish deployable frontend package",
      summary: "Build, screenshot verification, and production deployment instructions.",
      status: "done",
      priority: "high",
      owner: "Ariadne Release Verifier",
      source: "User request for independently deployable product frontend",
      decision: "code_task",
      changedFiles: ["package.json", "vite.config.ts", "README.md"],
      progress: [
        { time: "07:51", actor: "Release Verifier", kind: "verification", body: "Build must pass without Ariadne Python runtime." },
      ],
      reviewVerdict: "pass",
      memoryPath: ".ariadne/memory/frontend-release.json",
      nextTicketsPath: ".ariadne/artifacts/frontend/next_tickets.json",
      acceptance: [
        "npm run build succeeds.",
        "Frontend can be deployed as static assets.",
      ],
    },
  ],
  agents: [
    { name: "Ariadne Codex", description: "Codex agent for product implementation and integration.", backend: "Codex", status: "online", runs: 18, reasoning: "超高" },
    { name: "Ariadne Implementer", description: "Implementation agent for local-first Python and frontend changes.", backend: "Codex", status: "online", runs: 12, reasoning: "高" },
    { name: "Ariadne Reviewer", description: "Conservative review agent for architecture and regression risks.", backend: "Codex", status: "online", runs: 9, reasoning: "高" },
    { name: "Ariadne Release Verifier", description: "Release gate verifier for tests, CLI smoke, and evidence packets.", backend: "fake-codex", status: "idle", runs: 5, reasoning: "默认" },
  ],
  runtimes: [
    { machine: "local-mac", backend: "Codex", status: "online", version: "codex-cli flex", cost7d: "$0.51" },
    { machine: "local-mac", backend: "Claude", status: "online", version: "claude-code", cost7d: "$0.00" },
    { machine: "local-mac", backend: "fake-codex", status: "online", version: "deterministic", cost7d: "$0.00" },
  ],
  skills: [
    { name: "ariadne-multica-reference-lens", description: "Use Multica as architecture reference without copying backend code.", usedBy: ["Codex", "Reviewer"], updatedAt: "13 小时前" },
    { name: "ariadne-review-diff", description: "Review branch diff against ticket acceptance and safety boundaries.", usedBy: ["Reviewer", "Verifier"], updatedAt: "13 小时前" },
    { name: "ariadne-verification", description: "Run pytest, ruff, demo, export board, backend doctor, and verify_v1.", usedBy: ["Verifier"], updatedAt: "13 小时前" },
    { name: "ariadne-local-first-guardrails", description: "Keep external execution, Feishu writes, and hosted behavior gated.", usedBy: ["Codex", "Implementer"], updatedAt: "13 小时前" },
  ],
  inbox: [
    { id: "i-1", title: "ARI-FE-002 needs stronger timeline", body: "Reviewer asked for visible progress events in ticket detail.", time: "44 分钟", kind: "review" },
    { id: "i-2", title: "Goal direction updated", body: "Goal remains an input. Ticket state changes are the product center.", time: "1 小时", kind: "goal" },
    { id: "i-3", title: "Codex runtime config", body: "Use flex service tier. Do not run when quota is under the stop threshold.", time: "2 小时", kind: "blocker" },
    { id: "i-4", title: "Memory written", body: "Multica alignment notes are available for future planning.", time: "3 小时", kind: "memory" },
  ],
};
