import { Inbox, RefreshCw, RotateCcw, Wrench } from "lucide-react";
import { useEffect, useState } from "react";
import {
  acknowledgeInboxItem,
  createInboxRepairTicket,
  getInbox,
  rerunInboxAssignment,
  resolveInboxItem,
} from "../../shared/api/client";
import type { ApiInboxListItem, InboxActionResponse } from "../../shared/api/types";

function display(value: string | null | undefined, fallback = "Not recorded") {
  return value === null || value === undefined || value === "" ? fallback : value;
}

function statusLabel(status: string | null | undefined) {
  const labels: Record<string, string> = {
    acknowledged: "Acknowledged",
    blocked: "Blocked",
    critical: "Critical",
    high: "High",
    low: "Low",
    medium: "Medium",
    open: "Open",
    resolved: "Resolved",
  };
  return labels[status ?? ""] ?? status ?? "Unknown";
}

export function InboxPage() {
  const [items, setItems] = useState<ApiInboxListItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [busyAction, setBusyAction] = useState<string | null>(null);
  const [message, setMessage] = useState("");

  async function refreshInbox() {
    setLoading(true);
    setMessage("");
    try {
      const response = await getInbox();
      setItems(response.inbox);
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Failed to load inbox.");
    } finally {
      setLoading(false);
    }
  }

  async function runInboxAction(
    item: ApiInboxListItem,
    label: string,
    action: () => Promise<InboxActionResponse>,
  ) {
    if (busyAction) return;
    setBusyAction(`${label}:${item.id}`);
    setMessage(`${label}...`);
    try {
      const response = await action();
      await refreshInbox();
      setMessage(response.message || `${label} requested.`);
    } catch (error) {
      setMessage(error instanceof Error ? error.message : `${label} failed.`);
    } finally {
      setBusyAction(null);
    }
  }

  useEffect(() => {
    void refreshInbox();
  }, []);

  return (
    <section className="page full-bleed inbox-control-page">
      <header className="page-header">
        <div className="title-row">
          <Inbox size={17} />
          <h1>Inbox</h1>
          <span>{items.length}</span>
          <p>Actionable blockers and recovery items generated by agent runs.</p>
        </div>
        <div className="toolbar">
          <button type="button" onClick={() => void refreshInbox()}>
            <RefreshCw size={15} /> Refresh
          </button>
        </div>
      </header>
      {message ? <p className="action-message">{message}</p> : null}
      {loading ? <p className="empty-column">Loading inbox...</p> : null}
      <div className="inbox-list">
        {items.map((item) => (
          <article className="inbox-card" key={item.id}>
            <div className="inbox-main">
              <span className={`inbox-kind ${item.severity}`}>{statusLabel(item.severity)}</span>
              <strong>{display(item.issue_key, "No issue")}</strong>
              <p>{item.failure_reason}</p>
            </div>
            <div className="inbox-meta">
              <span>{statusLabel(item.status)}</span>
              <span>{item.action_type}</span>
              <span>{item.created_at}</span>
            </div>
            {item.resolution_note ? <small>{item.resolution_note}</small> : null}
            <div className="inbox-actions">
              <button
                disabled={busyAction !== null}
                type="button"
                onClick={() => void runInboxAction(item, "Repair", () => createInboxRepairTicket(item.id))}
              >
                <Wrench size={13} /> Repair
              </button>
              <button
                disabled={busyAction !== null}
                type="button"
                onClick={() => void runInboxAction(item, "Rerun", () => rerunInboxAssignment(item.id, { reason: "retry from workbench inbox" }))}
              >
                <RotateCcw size={13} /> Rerun
              </button>
              <button
                disabled={busyAction !== null}
                type="button"
                onClick={() => void runInboxAction(item, "Acknowledge", () => acknowledgeInboxItem(item.id, { note: "Acknowledged from Workbench." }))}
              >
                Acknowledge
              </button>
              <button
                disabled={busyAction !== null}
                type="button"
                onClick={() => void runInboxAction(item, "Resolve", () => resolveInboxItem(item.id, { note: "Resolved from Workbench." }))}
              >
                Resolve
              </button>
            </div>
          </article>
        ))}
        {!items.length && !loading ? <p className="empty-column">No inbox items projected.</p> : null}
      </div>
    </section>
  );
}
